### PR TITLE
fix: resolve error when changing token to basic auth

### LINKED ISSUE #3142: Change Authentication method misbehavior in v3
**Describe the bug**

Error returned when logging in `Cannot read properties of undefined (reading 'includes'). This is likely caused by the extension that contributes zowe.profileManagement.`

Seeing use basic auth as an option when basic auth is in place and not seeing token auth option 
It says User & Password but in description mentions login
I see this is same as in v2 now but still confusing 

Screenshot 2024-09-23 at 4 19 07 PM

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #3142 

## Release Notes

Milestone: 3.0.0 GA (or 3.1 if needed)

Changelog:

- Fixed issue where switching from token-based authentication to user/password would cause an error for nested profiles. [#3142](https://github.com/zowe/zowe-explorer-vscode/issues/3142)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer/src/configuration/Profiles.ts [hunk 1]
```diff
@@ -821,10 +821,11 @@ export class Profiles extends ProfilesCache {
         const profInfo = await this.getProfileInfo();
         const configApi = profInfo.getTeamConfig();
         const profAttrs = await this.getProfileFromConfig(profileName);
-        if (loginTokenType && loginTokenType.startsWith("apimlAuthenticationToken")) {
-            configApi.set(`${profAttrs.profLoc.jsonLoc}.secure`, []);
-        } else {
-            configApi.set(`${profAttrs.profLoc.jsonLoc}.secure`, ["tokenValue"]);
+        if (profAttrs.profLoc.jsonLoc) {
```
Comment (zFernand0) [inline packages/zowe-explorer/src/configuration/Profiles.ts:824]: Is it possible for `profAttrs` to be undefined here?
I guess I'm wondering about it since we did `?.` in `tokenAuthClearSecureArray` 😅

**Review by zFernand0 — APPROVED** [review]
thanks for handling possible undefined values for `jsonLoc` as well as reducing code duplication 🙏 
LGTM! 😋

File: packages/zowe-explorer/src/configuration/Profiles.ts (hunk 1 above)
Comment (traeok) [reply packages/zowe-explorer/src/configuration/Profiles.ts:824]: It shouldn't be possible as long as a profile matching `profileName` exists - and since we call the function with `serviceProfile.name` as the profile name parameter, ZE should always find attributes for that profile.

See `Profiles.handleSwitchAuthentication`, line 877:

```typescript
const serviceProfile = node.getProfile() ?? this.loadNamedProfile(node.label.toString().trim());
```

**Review by JillieBeanSim — COMMENTED** [review]
I still get the issue seen when I created bug but did come from extender, looking into an extender fix.

I am unable to test the API ML scenario with our API ML instance down atm, merging with the 2 approvals.

BTW: sample checks failing due to use of `^` fix is in release PR
