### PR TITLE
Fix data loss when moving member into empty PDS

### LINKED ISSUE #3950: Moving a member across LPARs into an empty PDS fails resulting in data loss
**Describe the bug**

When moving a member from one PDS to another on two different systems, if the target PDS is empty and open and the member is dropped into where it says 'No data sets found', it says the member's been moved successfully, but it does not appear in the target PDS. The member is also deleted off the source resulting in data loss.

**To Reproduce**

1. Create an empty PDS and open it
2. Move a member from a PDS from another system into that PDS
3. Drop it when hovered over 'No data sets found'

**Expected behavior**

I would expect the move to succeed and the member to appear in the target PDS.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Do you have secure credentials enabled?
- (Optional) Are you using a custom credential manager?

**Additional context**

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fixes #3950 by preventing PDS members from being dragged onto target nodes that shouldn't be allowed.

Also removes regex that could throw when it didn't match, and fixes members/files not being supported as drop targets.

### How to Test
**Member placeholder**
1. Create an empty PDS and expand it to show "No members found"
2. Move a member from another PDS into the empty PDS. Drop it when hovered over "No members found".
3. Verify that the member copied successfully without data loss

**Data Set placeholder**
1. Do a filter search in the Data Sets tree that has no results to show "No datasets found"
2. Move a PDS from another LPAR into the empty profile. Drop it when hovered over "No datasets found".
3. Verify that the PDS copied successfully without data loss

**Member/file targets**
* Move a member from one PDS into another one. Drop it when hovered over a member (not parent PDS).
* Move a file from one USS dir into another one. Drop it when hovered a file (not parent dir).

## Release Notes

Milestone: 3.4.0

Changelog: Fixed issue where moving a PDS member into "No members found" placeholder of an empty PDS deleted the member without transferring its data

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`
- [ ] New ZE APIs are tested with extender types that haven't adopted yet to determine breaking changes. Can use Zowe zFTP marketplace extension.

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer/src/trees/dataset/DatasetTree.ts [hunk 1]
```diff
@@ -225,7 +225,12 @@ export class DatasetTree extends ZoweTreeProvider<IZoweDatasetTreeNode> implemen
         if (!droppedItems) return;
 
         let target = targetNode;
-        if (!target) return;
+        if (!target) {
+            return;
+        } else if (SharedContext.isInformation(target)) {
+            // If node says "No data sets/members found", use its parent as target
+            target = target.getParent() as IZoweDatasetTreeNode;
```
[the remark this answers is not in the document]
Comment (zFernand0) [reply packages/zowe-explorer/src/trees/dataset/DatasetTree.ts:236]: I guess this makes sense.
Is the `target.getParent()` call guaranteed to return something other than `null` or `undefined`

File: packages/zowe-explorer/src/trees/dataset/DatasetTree.ts [hunk 2]
```diff
@@ -225,16 +229,22 @@ export class DatasetTree extends ZoweTreeProvider<IZoweDatasetTreeNode> implemen
         if (!droppedItems) return;
 
         let target = targetNode;
-        if (!target) return;
+        if (!target) {
+            return;
+        } else if (SharedContext.isDsMember(target) || SharedContext.isInformation(target)) {
+            // If node is member or says "No data sets/members found", use its parent as target
+            target = target.getParent() as IZoweDatasetTreeNode;
```
Comment (zFernand0) [inline packages/zowe-explorer/src/trees/dataset/DatasetTree.ts:236]: See copilot's comment above

File: packages/zowe-explorer/src/trees/dataset/DatasetTree.ts [hunk 3]
```diff
@@ -258,16 +268,18 @@ export class DatasetTree extends ZoweTreeProvider<IZoweDatasetTreeNode> implemen
...
+                Gui.errorMessage(vscode.l10n.t("Cannot drop a sequential dataset or a partitioned dataset into another partitioned dataset."));
+                return;
             }
             if ((SharedContext.isDsMember(node) || SharedContext.isPds(node)) && SharedContext.isDs(target)) {
                 Gui.errorMessage(vscode.l10n.t("Cannot drop a partitioned dataset or member into a sequential dataset."));
                 return;
             }
+            if (SharedContext.isDsMember(node) && SharedContext.isSession(target)) {
+                Gui.errorMessage(vscode.l10n.t("Cannot drop a dataset member into a profile node."));
+                return;
```
Comment (zFernand0) [inline packages/zowe-explorer/src/trees/dataset/DatasetTree.ts:281]: Thanks for individually checking the nodes being dragged and dropped. Makes it easier to maintain 🙏

File: packages/zowe-explorer/src/trees/dataset/DatasetTree.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (traeok) [reply packages/zowe-explorer/src/trees/dataset/DatasetTree.ts:236]: Since `ZoweDatasetNode` extends `ZoweTreeNode`, it should not be possible for `getParent` to return `undefined` as `mParent` is a required value in the `ZoweTreeNode` constructor. I would consider Copilot's comment a false positive unless we are incorrectly passing null/undefined as the parent elsewhere.

File: packages/zowe-explorer/src/trees/dataset/DatasetTree.ts [hunk 4]
```diff
@@ -163,7 +163,11 @@ export class DatasetTree extends ZoweTreeProvider<IZoweDatasetTreeNode> implemen
                 const entry = await DatasetFSProvider.instance.fetchDatasetAtUri(destUri);
                 if (entry == null) {
                     if (SharedContext.isDsMember(sourceNode)) {
-                        dsname = destUri.path.match(/^\/[^/]+\/(.*?)\/[^/]+$/)[1] + "(" + (sourceNode.getLabel() as string) + ")";
```
Comment (traeok) [inline packages/zowe-explorer/src/trees/dataset/DatasetTree.ts:166]: Thanks for removing this regex 👍

**Review by traeok — APPROVED** [review]
Thanks for the fix Timothy, tested both cases and the changes are working as expected.

One thing that felt a bit odd from a UX perspective: when dragging/dropping a PDS onto a profile with a different pattern set (that yields no results), the PDS disappears from the source profile. But its not clear to the user that the drag/drop was successful until they change their filter search to a pattern matching that PDS. Since the current pattern on the profile has no results anyway, I think it would help to update the pattern to match the moved data set(s). However, since this fix intends to resolve a more severe bug, I think we could address this separately.

File: packages/zowe-explorer/CHANGELOG.md [hunk 5]
```diff
@@ -36,6 +36,8 @@ All notable changes to the "vscode-extension-for-zowe" extension will be documen
 - Fixed release notes displaying when the Zowe Explorer version is downgraded. [#3966](https://github.com/zowe/zowe-explorer-vscode/pull/3966)
 - Fixed issue where favorited items caused a failure during initialization, specifically when the favorited item belongs to a profile type that's no longer registered or accessible. [#3962](https://github.com/zowe/zowe-explorer-vscode/pull/3962)
 - Fixed issue where the filesystem throws a vague `Unknown` FileSystemError if an API cannot be loaded for the given profile type. Now, if the API is inaccessible for the given profile type, an `Unavailable` error is thrown from the filesystem with more context. [#3962](https://github.com/zowe/zowe-explorer-vscode/pull/3962)
+- Fixed issue where moving a PDS member into "No members found" placeholder of an empty PDS deleted the member without transferring its data. [#3950](https://github.com/zowe/zowe-explorer-vscode/issues/3950)
```
Comment (anaxceron) [inline packages/zowe-explorer/CHANGELOG.md]:
```suggestion
- Fixed an issue where moving a PDS member into the "No members found" placeholder of an empty PDS deleted the member without transferring its data. [#3950](https://github.com/zowe/zowe-explorer-vscode/issues/3950)
```

**Review by anaxceron — APPROVED** [review]
