### PR TITLE
fix(v2): avoid data-loss when creating new members

### LINKED ISSUE #3327: tree(ds): Creating a new member with a conflicting name may cause data-loss
**Describe the bug**

Say that your HLQ.TEST.PDS contains a member called TEST. if you create a new member, and provide the name `TEST`, the data on your old member will be lost

**To Reproduce**

1. Create a PDS (HLQ.TEST.PDS)
2. Create a member called TEST
3. Add some content and save the member
4. Now, right click the PDS, and select "Create new member"
5. Name it TEST
6. Notice the conclict error:
image

And now your contents from step 3 are gone on the mainframe

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: 3.0.2

**Additional context**

This was discovered by @pujal0909 (Thank you! 🙏 ) when researching:
-  https://github.com/zowe/zowe-cli/issues/2349

### PR DESCRIPTION
**Pull request by zFernand0**
## Proposed changes

- Resolves #3327 

## Release Notes

Milestone: next V2 release

Changelog: Prevented data-loss when creating a new member called something that already exists.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by traeok — COMMENTED** [review]
Thanks for porting this over! I have a suggestion for the changelog, but I tested the functionality and everything LGTM

**Review by traeok — DISMISSED** [review]

File: packages/zowe-explorer/src/dataset/actions.ts [hunk 1]
```diff
@@ -412,10 +412,15 @@ export async function createMember(parent: api.IZoweDatasetTreeNode, datasetProv
     if (name) {
         const label = parent.label as string;
         const profile = parent.getProfile();
+        let replace: shouldReplace;
+        const dsMemberName = `${label}(${name})`;
         try {
-            await ZoweExplorerApiRegister.getMvsApi(profile).createDataSetMember(label + "(" + name + ")", {
-                responseTimeout: profile.profile?.responseTimeout,
-            });
+            replace = await determineReplacement(profile, dsMemberName, "mem");
```
Comment (t1m0thyj) [inline packages/zowe-explorer/src/dataset/actions.ts:418]: If I have previously opened the member and it was downloaded to the temp dir, then "Create New Member" and select "Replace", the contents are not overwritten. Is this expected behavior?

Comment (zFernand0) [reply packages/zowe-explorer/src/dataset/actions.ts:418]: Resolved in 955da02

File: packages/zowe-explorer/src/dataset/actions.ts [hunk 2]
```diff
@@ -420,6 +420,9 @@ export async function createMember(parent: api.IZoweDatasetTreeNode, datasetProv
                 await ZoweExplorerApiRegister.getMvsApi(profile).createDataSetMember(dsMemberName, {
                     responseTimeout: profile.profile?.responseTimeout,
                 });
+                if (replace === "replace") {
+                    deleteTempFile(dsMemberName, parent);
```
Comment (traeok) [inline packages/zowe-explorer/src/dataset/actions.ts:441]: We should probably `await` this function call, mostly so that the temp file is gone before `openDs` is called.

Comment (zFernand0) [reply packages/zowe-explorer/src/dataset/actions.ts:441]: Sorry for the confusion, the function didn't need to be async.
resolved in 3c3aee8f126d3f05d5bbc8c485209100af444306

**Review by JillieBeanSim — COMMENTED** [review]
Thanks for porting this fix over to v2 @zFernand0 for the most part all looks good to me.  One thing I noticed was that if the file that is being overwritten is opened the user has to pull from mainframe to get the latest from the file.
Sidenote!  I went to test this same scenario in the v2-lts branch and got the popup asking if I wanted to overwrite so is this PR fixing existing work or introducing the popup?  CHANGELOG states the popup is the addition here.

**Review by JillieBeanSim — APPROVED** [review]
LGTM, thanks for porting this fix @zFernand0.
per my last comment should we open a bug for the local file not updating if overwrite chosen? we may want to also check that scenario against v3 as well
