### PR TITLE
Fix: USS Tree Collapse When Opening Files with Encoding

### LINKED ISSUE #3932: Opening USS file with encoding sometimes collapses the whole tree
**Describe the bug**

Sometimes when opening a USS file with encoding (e.g. with binary encoding), the whole USS tree is collapsed down to the top level set from the initial filter. The tree is collapsed in a strange state too where the directory I had expanded previously has its arrow still down even after it is collapsed.

Image

**To Reproduce**

Not sure how to replicate reliably, it just sometimes happens and sometimes does not happen when opening some files with encoding in USS (default is IBM-1146).

**Expected behavior**

Tree to not collapse

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win11
- Zowe Explorer Version: 3.3.1
- (Optional) Zowe CLI Version:
- (Optional) Do you have secure credentials enabled?
- (Optional) Are you using a custom credential manager?

**Additional context**

### PR DESCRIPTION
**Pull request by ArghadeepDas-ibm**
## Proposed changes
Fixes : https://github.com/zowe/zowe-explorer-vscode/issues/3932
When opening a USS file with a specific encoding (e.g., binary encoding), the entire USS tree was collapsing down to the top level. 
Changes:
- setIcon() change: Replaced refreshElement() with nodeDataChanged(), limiting updates to repainting the node itself and avoiding unnecessary parent directory refreshes.
- setEncoding() change: Removed the dirty flag and documented why it’s no longer required, since visual updates are now fully handled through setIcon() → nodeDataChanged().

## Release Notes

Milestone:

Changelog: Fixed an issue where the whole USS tree is collapsed down to the top level set from the initial filter.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**All checks must pass before this pull request is reviewed by the Zowe Explorer squad.**

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`
- [ ] New ZE APIs are tested with extender types that haven't adopted yet to determine breaking changes. Can use Zowe zFTP marketplace extension.

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts [hunk 1]
```diff
@@ -446,7 +447,12 @@ export class ZoweUSSNode extends ZoweTreeNode implements IZoweUSSTreeNode {
     public setIcon(iconPath: { light: string; dark: string }): void {
         ZoweLogger.trace("ZoweUSSNode.setIcon called.");
         this.iconPath = iconPath;
-        vscode.commands.executeCommand("zowe.uss.refreshUSSInTree", this);
+        // Use nodeDataChanged instead of refreshElement to avoid collapsing the tree
+        // refreshElement marks the node as dirty which triggers a full parent refresh
+        const ussProvider = SharedTreeProviders.providers.uss;
+        if (ussProvider?.nodeDataChanged) {
+            ussProvider.nodeDataChanged(this);
+        }
```
Comment (traeok) [inline packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts]: Consider using optional chaining here to shorten this pattern into a single expression:

```suggestion
        SharedTreeProviders.providers.uss?.nodeDataChanged?.(this);
```

**Review by traeok — APPROVED** [review]
I wasn't able to reproduce this issue on main, but ultimately I think these changes are a step in the right direction (less refreshing). Tested and not seeing the collapse, so it LGTM. Can re-approve (if needed) after merge conflicts are resolved

File: packages/zowe-explorer/CHANGELOG.md [hunk 2]
```diff
@@ -27,6 +27,7 @@ All notable changes to the "vscode-extension-for-zowe" extension will be documen
 - Fixed an accessibility issue where screen readers could not access the job ID link after job submission. Replaced the inaccessible markdown link with keyboard-accessible "Open Job" button that can be navigated using Tab and activated with Enter or Space keys. [#4030](https://github.com/zowe/zowe-explorer-vscode/issues/4030)
 - Fixed an issue where focus was lost on a previously selected tree item after opening a Zowe resource (Data set, USS file, or Job) in the editor and closing it using `Ctrl+W`. Screen readers will now announce when focus is restored. [#4025](https://github.com/zowe/zowe-explorer-vscode/issues/4025)
 - Fixed an issue where loading profiles could wrongly assume token authentication if parent profile defines multiple auth types. [#4105](https://github.com/zowe/zowe-explorer-vscode/issues/4105)
+- Fixed an issue where the whole USS tree is collapsed down to the top level set from the initial filter.[#3932](https://github.com/zowe/zowe-explorer-vscode/issues/3932)
```
Comment (anaxceron) [inline packages/zowe-explorer/CHANGELOG.md]:
```suggestion
- Fixed an issue where the USS tree collapsed down to the top level set from the initial filter.[#3932](https://github.com/zowe/zowe-explorer-vscode/issues/3932)
```

**Review by anaxceron — APPROVED** [review]

**Review by traeok — APPROVED** [review]
Thanks Arghadeep! LGTM

**Review by awharn — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋
