### PR TITLE
fix(ds): Do not allow listing data sets while filter prompt is open

### LINKED ISSUE #3807: New update credentials window pops up 3 times in a row in DS tree
**Describe the bug**

When doing a data set search and a profile where password has expired, the new update credentials prompt now appears three times in a row when clicking the update credentials button (but only once with cancel as expected) - but only on the first time it pops up in a session!

Image

**To Reproduce**

1. Change/reset password for a profile on the MF
2. Click search data sets on profile
3. See update credentials prompt
4. Click "update credentials"
5. Prompt will appear again
6. Credentials quick pick appears but can't type anything in because...
7. Repeat steps 4/5 twice more
8. Finally prompt is gone, can update credentials

**Expected behavior**

Clicking update credentials prompt should not reappear

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10
- Zowe Explorer Version: v3.3.0-SNAPSHOT (latest main build)
- (Optional) Zowe CLI Version:
- (Optional) Do you have secure credentials enabled? Yes
- (Optional) Are you using a custom credential manager? No

**Additional context**

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #3807  

### How to test

Enable data set list pagination before trying these steps.

#### Invalid credentials, user updates

- Set invalid credentials on a profile
- Enter in a pattern in the data set filter prompt
- Encounter the auth prompt. Respond "Update Credentials" and enter new creds
- The auth prompt disappears and data sets are listed.

#### Invalid credentials, user cancels

- Set invalid credentials on a profile
- Enter in a pattern in the data set filter prompt
- Encounter the auth prompt. Respond "Cancel"
- The auth prompt disappears and the profile shows "No data sets found".
- Refresh this profile and encounter the same prompt. Select "Cancel." 
- The prompt no longer re-appears until the user enters a new filter or refreshes the profile again. 

## Release Notes

Milestone: 3.3.0 hopefully - if not 3.3.1

Changelog:

Fixed issue where the `getChildren` function made requests repeatedly while the data set filter prompt was open, causing repeated authentication prompts and excessive requests for listing data sets. 

No changelog for ZE API as the change has no impact on consumers/users

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [x] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [x] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Comment by JWaters02** [comment]
Hi trae, this _almost_ works. 

Update credentials button click works properly now. And it pops up when I'd expect it to when opening from data sets and favourites.

Cancel button click works properly in 75% of cases, but a couple of times while clicking around different buttons, (while I had invalid credentials set), the prompt has popped up twice in a row and once thrice in a row. But I can't seem to pin down exactly when thrice in a row happens. It does so when clicking on a favourited PDS (but not during any subsequent attempts, even after reloading the window).

However I can replicate the twice in a row popup:
1. Update profile to have invalid credentials
2. Try to filter on data set profile
3. Click cancel (this will work as expected)
4. Try to filter on same profile again
5. Click cancel, then prompt pops up for second time, cancel once more.

**Review by JWaters02 — CHANGES_REQUESTED** [review]
Hi trae, this _almost_ works. 

Update credentials button click works properly now. And it pops up when I'd expect it to when opening from data sets and favourites.

Cancel button click works properly in 75% of cases, but a couple of times while clicking around different buttons, (while I had invalid credentials set), the prompt has popped up twice in a row and once thrice in a row. But I can't seem to pin down exactly when thrice in a row happens. It does so when clicking on a favourited PDS (but not during any subsequent attempts, even after reloading the window).

However I can replicate the twice in a row popup:
1. Update profile to have invalid credentials
2. Try to filter on data set profile
3. Click cancel (this will work as expected)
4. Try to filter on same profile again
5. Click cancel, then prompt pops up for second time, cancel once more.

**Review by anaxceron — APPROVED** [review]

**Review by JWaters02 — APPROVED** [review]
Thanks Trae I cannot replicate the issue anymore (spent a while clicking around in different things).

File: packages/zowe-explorer/src/trees/dataset/DatasetTree.ts [hunk 1]
```diff
@@ -1356,6 +1357,7 @@ export class DatasetTree extends ZoweTreeProvider<IZoweDatasetTreeNode> implemen
                 quickpick.hide();
                 if (!choice) {
                     Gui.showMessage(vscode.l10n.t("No selection made. Operation cancelled."));
+                    node.inFilterPrompt = false;
```
Comment (t1m0thyj) [inline packages/zowe-explorer/src/trees/dataset/DatasetTree.ts]: If we add more cases to this function in the future that return early, it seems easy to forget that we should reset `inFilterPrompt` to false. Should we wrap the code in this function in a try/finally block so it always get reset to false at the end?

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

File: packages/zowe-explorer/src/trees/dataset/DatasetTree.ts (hunk 1 above)
Comment (traeok) [reply packages/zowe-explorer/src/trees/dataset/DatasetTree.ts]: Addressed in f1684c8

**Review by t1m0thyj — APPROVED** [review]
