### PR TITLE
fix(ftp): Only return 401 error if authentication fails

### LINKED ISSUE #3496: zftp profile gives "Rest API failure with HTTP(S) status 401 Authentication error."
**Describe the bug**

Credentials fail to load in `zftp` whether plain text or in secure credential store with these error logs.

```
[2025/03/05 10:23:35] [INFO] Profile validation failed for zftp.
[2025/03/05 10:23:35] [ERROR] Error: Rest API failure with HTTP(S) status 401 Authentication error.
{
  errorDetails: [o [Error]: Rest API failure with HTTP(S) status 401 Authentication error.
  	at U.<anonymous> (/Users/----/.vscode/extensions/zowe.zowe-explorer-ftp-extension-3.1.1/out/src/main.extension.js:49:13623)
  	at Generator.throw (<anonymous>)
  	at y (/Users/---/.vscode/extensions/zowe.zowe-explorer-ftp-extension-3.1.1/out/src/main.extension.js:49:12357)] {
    mDetails: {
      msg: 'Rest API failure with HTTP(S) status 401 Authentication error.',
      errorCode: '401'
    },
    mMessage: 'Rest API failure with HTTP(S) status 401 Authentication error.'
  },
  profile: undefined
}
[2025/03/05 10:23:59] [ERROR] Profile zftp is inactive. Please check if your Zowe server is active or if the URL and port in your profile is correct.
```

`zftp` CLI for Zowe CLI works (as does z/OSMF & zssh).  The credentials and Zowe Explorer tree views for z/OSMF and zssh work as well.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #3496 by refactoring the `AbstractFtpApi.getStatus` function to only build & return a 401 error when the FTP client fails to authenticate.

## Release Notes

Milestone: 3.1.2

Changelog:

- Fixed issue where FTP client errors incorrectly triggered authentication prompts instead of showing appropriate error messages.

No changelog for the API as the change has no impact to extenders and the root cause is from the FTP extension logic.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [x] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer-api/src/profiles/AuthHandler.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ export type ProfileLike = string | imperative.IProfileLoaded;
 export class AuthHandler {
     private static authPromptLocks = new Map<string, Mutex>();
     private static profileLocks = new Map<string, Mutex>();
-    private static enabledProfileTypes: Set<string> = new Set(["zosmf"]);
+    private static enabledProfileTypes: Set<string> = new Set(["zosmf", "zftp"]);
```
Comment (zFernand0) [inline packages/zowe-explorer-api/src/profiles/AuthHandler.ts:43]: Dumb question: Is this something we will need to do for other extenders?

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

File: packages/zowe-explorer-api/src/profiles/AuthHandler.ts (hunk 1 above)
Comment (traeok) [reply packages/zowe-explorer-api/src/profiles/AuthHandler.ts:43]: Extenders can enable locks for their profile types using the `AuthHandler.enableLocksForType` function, but I've kept the profile types to just the ones we maintain to avoid breaking changes. 

If we want to in v4, we could remove the check entirely and use the profile locks for all types 😋

Comment (zFernand0) [reply packages/zowe-explorer-api/src/profiles/AuthHandler.ts:43]: I would always be in favor of consistency. 😋 
But C4 sounds good 👍

Comment (JillieBeanSim) [reply packages/zowe-explorer-api/src/profiles/AuthHandler.ts:43]: since we use the zFTP extension as a sample should we have the zFTP extension share how extenders are to enable the lock.  Having the zFTP ext make the `AuthHandler.enableLocksForType` call?

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
thanks for working on this @traeok, left a change request

**Comment by traeok** [comment]
> thanks for working on this @traeok, left a change request

> since we use the zFTP extension as a sample we should have the zFTP extension share how extenders are to enable the lock.  Having the zFTP ext make the `AuthHandler.enableLocksForType` call

Thanks for the suggestion, addressed in c630002 👍

**Review by anaxceron — APPROVED** [review]
