### PR TITLE
Fix for extender break in USS filter search

### LINKED ISSUE #4159: Unable to list USS files with extenders in 3.5.0
Apologies , data sets & jobs looks good but get this with extender type in uss which I don't experience with 3.4.2. This is experienced after creating faves, then a refresh of VSC, and then expand Favorites.

Image

Also, this issue stated above is now becoming present in follow up reviews when running debugger to test but not with vs code not in debugger mode with 3.4.2.  I will try testing on main to see if it's there. 
Update I am seeing this on all branches now, even cleared my Code Cache and removed all favorites. I can't get out of it and the search in USS was initially working when I started testing. 

I do not see it on the release/3.4 branch

Finally, I found it working through commits into main and [this](https://github.com/zowe/zowe-explorer-vscode/commit/d30716323fefe58e290804833c03d285460c2ef3) is the culprit that breaks extenders search in uss treeview, [Stat fetch default (](https://github.com/zowe/zowe-explorer-vscode/commit/d30716323fefe58e290804833c03d285460c2ef3)https://github.com/zowe/zowe-explorer-vscode/pull/3963[)](https://github.com/zowe/zowe-explorer-vscode/commit/d30716323fefe58e290804833c03d285460c2ef3)

_Originally posted by @JillieBeanSim in https://github.com/zowe/zowe-explorer-vscode/pull/4146#pullrequestreview-4036878347_

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

fix extender break with filter search in uss tree view

## Release Notes

Milestone:

Changelog: n/a bug was not published yet

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**All checks must pass before this pull request is reviewed by the Zowe Explorer squad.**

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`
- [ ] New ZE APIs are tested with extender types that haven't adopted yet to determine breaking changes. Can use Zowe zFTP marketplace extension.

**Code coverage**

- [ ] There is coverage for the code that I have added
- [x] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer/src/trees/uss/UssFSProvider.ts [hunk 1]
```diff
@@ -260,9 +262,21 @@ export class UssFSProvider extends BaseProvider implements vscode.FileSystemProv
...
-                this._createDirectoryRecursive(uri);
+            if (response.success && !keepRelative && !this.exists(uri)) {
+                const rawItems = response.apiResponse?.items ?? [];
+                const uriBasename = path.posix.basename(uri.path);
+                // Classic z/OSMF responses include a "." entry (mode "d") as the first item.
+                // Some extenders omit that entry and return only child entries. In that case,
+                // detect a directory listing by verifying that no raw item is a non-directory
+                // file whose name matches the URI basename. Such an item would indicate that
+                // fileList was called on a plain file and we must not create a directory.
+                const hasSelfAsFile = rawItems.some((item) => item.name === uriBasename && !(item.mode as string | undefined)?.startsWith("d"));
```
Comment (t1m0thyj) [inline packages/zowe-explorer/src/trees/uss/UssFSProvider.ts]: Thanks for catching this @JillieBeanSim! Generally the fix makes sense, but I have some questions about it.

We already do something similar for listing USS files with FTP at the ZE API level:
https://github.com/zowe/zowe-explorer-vscode/blob/4bf2aa3f5161acbfa47de0b69d5ccb4420430ea0/packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts#L51-L53

1. Is making the change in the `UssFSProvider` the best place to do it, or would it be better to do at the ZE API level for RSE like we do for FTP? It seems like extenders may expect the `.` and `..` entries to be returned for directories since z/OSMF does it.
2. What happens in the case of a directory that contains a file whose name matches the URI basename? For example, if I'm listing a directory `/u/users/ibmuser/temp` and it contains an extensionless file named `temp`.

Comment (JillieBeanSim) [reply packages/zowe-explorer/src/trees/uss/UssFSProvider.ts]: that change in zftp could be why the issues aren't seen there but a breaking change was introduced. we control the ftp and can adopt changes when or right after introduced.  We should introduce the ftp changes separately with new ZE API changes so testers can test backwards compatibility making sure no breaking changes have been introduced.  With the scenario working with marketplace and not main for extenders that don't already use the latest ZE API dependency (main atm) means backwards compatibility was not considered.

Comment (JillieBeanSim) [reply packages/zowe-explorer/src/trees/uss/UssFSProvider.ts]: maybe we were handling it in ZE prior to the breaking change introduced

File: packages/zowe-explorer/src/trees/uss/UssFSProvider.ts [hunk 2]
```diff
@@ -260,9 +262,28 @@ export class UssFSProvider extends BaseProvider implements vscode.FileSystemProv
...
             response = await ZoweExplorerApiRegister.getUssApi(loadedProfile).fileList(ussPath);
 
-            // If request was successful, create directories for the path if it doesn't exist
-            if (response.success && !keepRelative && response.apiResponse.items?.[0]?.mode?.startsWith("d") && !this.exists(uri)) {
-                this._createDirectoryRecursive(uri);
+            if (response.success && !keepRelative && !this.exists(uri)) {
+                const rawItems = response.apiResponse?.items ?? [];
+                const uriBasename = path.posix.basename(uri.path);
+                // Classic z/OSMF responses include a "." entry (mode "d") as the first item.
+                // Some extenders omit that entry and return only child entries. In that case,
```
Comment (traeok) [inline packages/zowe-explorer/src/trees/uss/UssFSProvider.ts:269]: While I think this aligns with what we do in FTP, with this change we are now operating under a different assumption: that the extender is expected to return the full path if the user lists a file path instead of a directory path.

I think this is what necessitates the need for defining expectations around listing files in v4, so that all of our APIs are on the same page when it comes to expected use cases 😋

**Review by traeok — COMMENTED** [review]
Doing some testing now, plan to approve if everything goes smoothly 😋 
Thanks Billie

File: packages/zowe-explorer/src/trees/uss/UssFSProvider.ts (hunk 2 above)
Comment (JillieBeanSim) [reply packages/zowe-explorer/src/trees/uss/UssFSProvider.ts:269]: yes sounds good for v4 conformance

**Review by traeok — APPROVED** [review]

**Comment by traeok** [comment]
Audit is failing, but its from a deprecated endpoint and not from changes on this branch: 

```
ERR_PNPM_AUDIT_BAD_RESPONSE  The audit endpoint (at https://registry.npmjs.org/-/npm/v1/security/audits) responded with 410: {"error":"This endpoint is being retired. Use the bulk advisory endpoint instead. See the following docs for more info: https://api-docs.npmjs.com/#tag/Audit"}
```

See here for more info: 
- https://github.com/pnpm/pnpm/issues/11265
- https://github.com/orgs/community/discussions/192768

**Comment by JillieBeanSim** [comment]
> Audit is failing, but its from a deprecated endpoint and not from changes on this branch:
> 
> ```
> ERR_PNPM_AUDIT_BAD_RESPONSE  The audit endpoint (at https://registry.npmjs.org/-/npm/v1/security/audits) responded with 410: {"error":"This endpoint is being retired. Use the bulk advisory endpoint instead. See the following docs for more info: https://api-docs.npmjs.com/#tag/Audit"}
> ```
> 
> See here for more info:
> 
> * [`pnpm audit` fails with 410: npm registry has retired legacy audit endpoints pnpm/pnpm#11265](https://github.com/pnpm/pnpm/issues/11265)
> * https://github.com/orgs/community/discussions/192768

thanks @traeok for looking into this.  That's crazy it's affecting pnpm and yarn and no fix available with vulnerabilities showing up every other day 🤦🏻

**Review by jace-roell — APPROVED** [review]
LGTM! Thanks Billie
