### PR TITLE
fix(ds): Prevent deleting members for the wrong profile

### LINKED ISSUE #3883: Delete action incorrectly assumes parent PDS is in tree view selection
**Describe the bug**

Say that I have the same PDS on two different LPARs: Profile A and Profile B.

If I have the same PDS name selected under profile _A_, but then right click on a PDS member under the _same_ PDS name in profile _B_ to delete it... the data set member under profile A is deleted. 🫨 

This seems pretty severe and I ran into it while doing manual tests for another issue 😅 

**To Reproduce**

1. Create the same PDS name on two different systems with the same set of members
2. Search for that PDS under both profiles
3. Expand the PDS under both profiles
4. Select the PDS under profile A
5. Right-click on a member in profile B and select "Delete"
6. Notice that the member in profile A is deleted (actual) rather than profile B (expected)

**Expected behavior**

The delete action for members should not consider my tree view selection, only the item that was selected. The parent should be trivial to determine based on the selected PDS member(s).

**Desktop (please complete the following information):**

- OS: Windows 11
- Zowe Explorer Version: build from `main` branch / 3.3.0 / 3.4.0-snapshot

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fixes #3883

## How to Test

1. In Zowe Explorer, open a PDS member across two separate profiles. The data set name and member name must both match. For example, `IBMUSER.PDS(TESTMEM)` on both LPAR1 and LPAR2.
2. Click the member node associated with LPAR1 to make it the focused node in Data Sets tree. Then right-click (without selecting) the member node associated with LPAR2, and select the "Delete" action.
3. Verify that the member was deleted on LPAR2, not LPAR1.

## Release Notes

Milestone: 3.1.1

Changelog: Fixed an issue where the Delete action in the Data Sets tree could delete a PDS member previously selected in the tree rather than the one that was right-clicked

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer/src/trees/dataset/DatasetActions.ts [hunk 1]
```diff
@@ -653,17 +645,10 @@ export class DatasetActions {
...
-                (selectedNode) => selectedNode.getParent() && !SharedContext.isSession(selectedNode) && !SharedContext.isInformation(selectedNode)
-            ) as IZoweDatasetTreeNode[];
-        } else {
-            if (node.getParent() && !SharedContext.isSession(node) && !SharedContext.isInformation(node)) {
-                nodes = [];
-                nodes.push(node);
-            }
-        }
+        // Filter out sessions and information messages
+        let nodes = selectedNodes.filter(
```
Comment (traeok) [inline packages/zowe-explorer/src/trees/dataset/DatasetActions.ts]: (nitpick) `nodes` can be made `const` if lines 703-710 were refactored to return early, instead of setting `nodes` to an empty array. That said, I'm not expecting you to change existing code that's not entirely related to this fix, just thinking of ways to optimize where possible 🙂 

It is a bit odd that those aforementioned lines have a pattern of `await Gui.infoMessage(...).then(...)` - but this code is pre-existing, so not requesting changes 😋

**Review by traeok — APPROVED** [review]
LGTM, thanks for the fix!

**Review by pujal0909 — CHANGES_REQUESTED** [review]
Thanks @t1m0thyj! This resolves the issue of the member being deleted off the wrong profile, but I am getting this error when selecting a PDS on one LPAR and right clicking without selecting a PDS (named the same) on another LPAR. It seems to delete off the correct profile, but this error appears. Not sure if this is related to your changes or not.

image

File: packages/zowe-explorer/src/trees/dataset/DatasetActions.ts (hunk 1 above)
Comment (t1m0thyj) [reply packages/zowe-explorer/src/trees/dataset/DatasetActions.ts]: Addressed in https://github.com/zowe/zowe-explorer-vscode/pull/3882/commits/60f8fa3684c4f6eda03243f6888c348087170ad2
