### PR TITLE
fix: Only show "No configs detected" prompt if ZE opened

### LINKED ISSUE #3280: Zowe Explorer Prompts Credentials for non z/OS Projects
If I open VS Code for a project that has nothing to do with mainframe, I continuously encounter this prompt:

image

It seems like this prompt should only occur when I actually try to open the Zowe Explorer Extension 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #3280

## Release Notes

Milestone: 3.0.3

Changelog:

- Fixed issue where Zowe Explorer would present the "No configs detected" notification before it was used in a workspace without a Zowe config. [#3280](https://github.com/zowe/zowe-explorer-vscode/issues/3280)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer/src/trees/dataset/DatasetInit.ts [hunk 1]
```diff
@@ -30,6 +31,12 @@ export class DatasetInit {
         return tree;
     }
 
+    public static async datasetTreeVisibilityChanged(this: void, e: vscode.TreeViewVisibilityChangeEvent): Promise<void> {
+        if (e.visible) {
+            await ProfilesUtils.promptUserWithNoConfigs();
+        }
+    }
```
Comment (zFernand0) [inline packages/zowe-explorer/src/trees/dataset/DatasetInit.ts:38]: I like the idea of having a set of actions that can be performed as long as a specific tree is visible.

I know this is to fix one specific issue, but...

I'm curious if we should either do the same kind of visibility detection across the board, or in the shared init.

The only reason why I'm asking is because the `ProfilesUtils.promptUserWithNoConfigs` doesn't feel to be DS specific  😅

**Review by zFernand0 — CHANGES_REQUESTED** [review]
LGTM! 😋 

Left a quick request, and please feel free to dismiss my requested-changes if you believe it doesn't make much sense for this fix 😋

File: packages/zowe-explorer/src/trees/dataset/DatasetInit.ts (hunk 1 above)
Comment (traeok) [reply packages/zowe-explorer/src/trees/dataset/DatasetInit.ts:38]: This dialog is mostly to help new users who don't know that they don't have any Zowe client configurations. This means that when the Zowe Explorer panel is opened for the first time, it will prompt the user if no client configurations are detected. Since the Data Sets tree is the first to initialize, the event listener will do the prompting if no client configs were detected once the data sets tree is opened.

While this isn't specific to the data sets tree, I figured that it made sense to use that tree for the event subscription as it is the first tree that's initialized. I don't think there's a way to detect when Zowe Explorer is opened from the Side Bar - if there was, I think that would be the best approach. That's why I put the event on one of the tree views as it will initialize when the ZE icon is clicked in the Side Bar.

Comment (zFernand0) [reply packages/zowe-explorer/src/trees/dataset/DatasetInit.ts:38]: Makes sense to keep using the first tree in our activations sequence.
I just hope we find this whenever we need to make other "if-visible" operations 😋

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Review by anaxceron — APPROVED** [review]

File: packages/zowe-explorer/src/utils/ProfilesUtils.ts [hunk 2]
```diff
@@ -28,6 +28,7 @@ export enum ProfilesConvertStatus {
 
 export class ProfilesUtils {
     public static PROFILE_SECURITY: string | boolean = Constants.ZOWE_CLI_SCM;
+    private static noConfigDialogShown: boolean = false;
```
Comment (t1m0thyj) [inline packages/zowe-explorer/src/utils/ProfilesUtils.ts:31]: Should we rename this variable so it doesn't start with the word `no`? Please feel free to ignore, I'm definitely being picky but this was a bit hard to read because it seemed like a double negative 😋 

```suggestion
    private static createConfigDialogShown: boolean = false;
```

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks for this fix @traeok ❤️

**Review by zFernand0 — APPROVED** [review]
LGTM as-is 😋 
Up to y'all if we should wait for this final comment to be addressed:
- https://github.com/zowe/zowe-explorer-vscode/pull/3281#discussion_r1823352803
