### PR TITLE
Fix 4141: Updating credentials does not refresh profile in tree

### LINKED ISSUE #4141: Updating credentials does not refresh profile in tree
**Describe the bug**

When listing data sets using a profile with expired credentials, entering the correct credentials leaves the UI in a bad state.

**To Reproduce**

1. Have outdated credentials for a profile
2. List datasets with the profile
3. ZE prompts you to update password
4. You update it and see that nothing happens (datasets are NOT listed)
5. The profile icon shows a red badge (bad credentials)
6. Try to list datasets again
7. Datasets are listed without any issue but the red badge remains

**Expected behavior**

After entering the correct credentials, profile icon should have green badge and list should come back without retry required.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Do you have secure credentials enabled?
- (Optional) Are you using a custom credential manager?

**Additional context**

### PR DESCRIPTION
**Pull request by jellypuno**
## Proposed changes
This PR fixes issue #4141 Updating credentials does not refresh profile in tree

**Profile Validation Improvements:**

* Updated `Profiles.ts` so that if `AuthUtils.errorHandling` resolves to `true` (indicating credentials were updated), the profile validation logic will retry checking the current profile, improving reliability and user experience.

**Testing:**

* Added a unit test to verify that `validateProfiles` retries `checkCurrentProfile` if `errorHandling` returns `true`, ensuring this scenario is properly covered.

Recording 2026-04-09 185925

## Release Notes

Milestone:

Changelog:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**All checks must pass before this pull request is reviewed by the Zowe Explorer squad.**

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [x] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`
- [ ] New ZE APIs are tested with extender types that haven't adopted yet to determine breaking changes. Can use Zowe zFTP marketplace extension.

**Code coverage**

- [x] There is coverage for the code that I have added
- [x] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

## Further comments

This change was **NOT** generated by AI 😆 After all these years I'm still haunted by profiles 👻 

btw, checkCurrentProfile both exists in [Profiles.ts](https://github.com/zowe/zowe-explorer-vscode/blob/main/packages/zowe-explorer/src/configuration/Profiles.ts#L161) and [ZoweTreeProvider.ts](https://github.com/zowe/zowe-explorer-vscode/blob/main/packages/zowe-explorer/src/trees/ZoweTreeProvider.ts#L269). it was really confusing 😵  I stopped using AI because it got confused as well! 🤣  If I was the one who contributed that, apologies! 🙏

### CODE REVIEW

**Comment by JWaters02** [comment]
Awesome, it works, I tried various scenarios that I'd typically be in when using ZE at work and am finding it very reliable. I will also test on my work system tomorrow. Thanks

**Comment by JWaters02** [comment]
Oh darn, almost everything is working correctly on work system, but I also remembered to try saving a member and have found that I still get the same error I reported previously when trying to save the member after just updating my credentials to valid ones. Same steps to reproduce and same workaround to get it to save.

**Comment by jellypuno** [comment]
@JWaters02 did you update the creds through this error message?
image


or did you update the profile through manage profile > update credentials? 
The code I added goes through that auth error handling.

**Comment by JWaters02** [comment]
Hi, I can replicate the same not being able to save issue both when I click "Update credentials" on the prompt to update then search data sets, and when I right click profile -> manage profile -> update credentials then search data sets.

So just to clarify the steps for your replication:
1. Setup: right click profile -> manage profile -> update credentials, enter 'blah' as username
2. Reload VS Code
3. Right click profile -> manage profile -> update credentials, enter correct credentials
4. Search data sets on profile
5. Open data set
6. Try to save, see error messages

OR

1. Setup: right click profile -> manage profile -> update credentials, enter 'blah' as username
2. Reload VS Code
3. Try to search data sets on profile, get update credentials prompt
4. Click update credentials
5. Enter correct credentials
6. Search data sets on profile
7. Open data set
8. Try to save, see error messages

**Comment by jellypuno** [comment]
@JWaters02 It doesn't happen to me. I tried both 

fix4141

did you install and build first? can you send a gif?

**Comment by JWaters02** [comment]
I installed the vsix build created by the actions from in this PR https://github.com/zowe/zowe-explorer-vscode/actions/runs/24203523749?pr=4170
I verify I am on this PR because the other bug where the profile still shows as inactive is fixed here

The two things I notice in your gif that are different to what I am doing:
- I am reloading vscode after the setup/first step and you are not (I reload so I am in the situation that I open vscode when my password has expired overnight and I get the update credentials prompt as the first thing when I use ZE)
- I am editing a PDS member and you are editing on a sequential data set

I can't send you a video until either later tonight or tomorrow because I can't share my work system and I am in the office today, but I will do when I can if you can't replicate by then. Thanks

**Comment by jellypuno** [comment]
@JWaters02 I reloaded it too but I am on debug. I will try installing the vsix file and edit a pds member

**Comment by JWaters02** [comment]
Replicating in debug mode with zxplore system

https://github.com/user-attachments/assets/c5827b1b-b3eb-4a66-a301-100957818707

**Comment by jellypuno** [comment]
So there's an issue in the cached profile read [in this line](https://github.com/zowe/zowe-explorer-vscode/blob/main/packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts#L787).
The var `entry.metadata.profile` still contains the old profile information, even though imperative.IProfileLoaded is already updated. I am not sure why.

@JWaters02 can you please try again?

**Comment by jellypuno** [comment]
@JillieBeanSim @zFernand0 
Not sure if the changes that I introduced in `DatasetFSProvider.ts` is correct because it looks like `entry.metadata.profile` is used in a lot of functions and there's probably a reason why we are using cached information. My guess is because of extenders?

My suggestion is to move this error into a different bug ticket where we should investigate how to update the cached profile information properly after updating the credentials. If you agree, I will remove the changes that I've done in `DatasetFSProvider.ts`

**Comment by traeok** [comment]
It could make sense to separate the issue around caching into a separate problem.. That said, it seems like some of the logic in the FSPs has taken a step backward, as we already implemented fixes around FSP profile caching in previous PRs:

- https://github.com/zowe/zowe-explorer-vscode/pull/3457
- https://github.com/zowe/zowe-explorer-vscode/pull/3531

**Comment by jellypuno** [comment]
@traeok ok, what does it mean for me? Did I miss some commits and my branch didn't update properly?

**Comment by traeok** [comment]
> @traeok ok, what does it mean for me? Did I miss some commits and my branch didn't update properly?

No worries, your branch is fine. It was just an observation that the issue you mentioned was reintroduced into main, specifically regarding the profile caching that we resolved in the past. We can resolve it separately.

**Comment by JWaters02** [comment]
So just to check, are we saying that this PR is to fix the first issue and that another one will be to fix the problem of not being able to save members after updating invalid credentials? If that is the case then I am happy to approve this one once the attempted fix for the second issue is reverted (I haven't had the chance to test it yet - apologies for that). 

Also I wonder, since this profile caching issue seems very easy to reappear in main without noticing, do we need some kind of tests to make sure that the bug is not accidentally reintroduced? Thanks

File: .gitignore [hunk 1]
```diff
@@ -32,3 +32,4 @@ package.nls.*.json
 bundle.l10n.*.json
 bundle.l10n.json.template
 zedc/target
+/.skills
```
Comment (JWaters02) [inline .gitignore]: What is this `.skills` folder for?

**Review by JWaters02 — APPROVED** [review]
Bug fix is working as expected, thanks

File: .gitignore (hunk 1 above)
Comment (jellypuno) [reply .gitignore]: oh no! I should remove that 😥 It's for AI

Comment (zFernand0) [reply .gitignore]: I think it should be removed, at least until we have a proper Agents.md file in the project.

Could the skills be moved to the user-homedir?

File: packages/zowe-explorer/src/configuration/Profiles.ts [hunk 2]
```diff
@@ -874,7 +874,11 @@ export class Profiles extends ProfilesCache {
                         comment: [`The profile name`],
                     })
                 );
-                await AuthUtils.errorHandling(error, { profile: theProfile });
+                const updated = await AuthUtils.errorHandling(error, { profile: theProfile });
+                if (updated) {
+                    this.profilesForValidation = this.profilesForValidation.filter((p) => p.name !== theProfile.name);
+                    return this.checkCurrentProfile(theProfile);
+                }
```
Comment (JillieBeanSim) [inline packages/zowe-explorer/src/configuration/Profiles.ts:881]: I have a concern about this new check. When `AuthUtils.errorHandling()]` returns true, `Profiles.validateProfiles()` removes the cached entry and immediately calls `Profiles.checkCurrentProfile()` again. If the profile remains invalid and errorHandling() keeps returning true, this creates an unbounded retry loop instead of surfacing the inactive state. The new unit test only covers the success-on-retry case and does not guard against repeated failure.

**Review by JillieBeanSim — COMMENTED** [review]
Thanks for working on this fix @jellypuno. I did leave one concern while looking over the code changes

File: packages/zowe-explorer/src/configuration/Profiles.ts (hunk 2 above)
Comment (jellypuno) [reply packages/zowe-explorer/src/configuration/Profiles.ts:881]: hmm.. let me test this one

Comment (traeok) [reply packages/zowe-explorer/src/configuration/Profiles.ts:881]: `errorHandling` only returns `true` if the user entered in new credentials, but we don't know that the credentials are valid until we make another request. Is the suggestion to cap the amount of credential retries for a single profile before its automatically locked?

Granted, the "repeated failures" could be problematic now that z/OSMF requires auth for the endpoint we query w/ `getStatus`... if the user enters in bad creds, they get prompted again during profile validation, and this continues until the user enters in correct creds or hits Cancel. 🤔 

Cancel should lock the profile, preventing any more prompts - we also clarify this within the credential prompt for the user.

Comment (traeok) [reply packages/zowe-explorer/src/configuration/Profiles.ts:881]: Discussed in standup and felt it was best to file this as a separate issue - there is currently no cap on how many times it will retry w/ newly-entered creds. Filed #4200 to add this cap

Comment (jellypuno) [reply packages/zowe-explorer/src/configuration/Profiles.ts:881]: @traeok @JillieBeanSim 

> but we don't know that the credentials are valid until we make another request.

I thought this.checkCurrentProfile does the validation. It shows me if the profile has valid credentials and can access zosmf apis

https://github.com/user-attachments/assets/ae63de50-d6cf-4147-9594-75f1817c6431

> Discussed in standup and felt it was best to file this as a separate issue - there is currently no cap on how many times it will retry w/ newly-entered creds. Filed https://github.com/zowe/zowe-explorer-vscode/issues/4200 to add this cap

Cool! I was trying to cancel the loop by adding a retry counter but, you're right,  we should discuss how many retries a customer can make.

Comment (t1m0thyj) [reply packages/zowe-explorer/src/configuration/Profiles.ts:881]: > I thought this.checkCurrentProfile does the validation. It shows me if the profile has valid credentials and can access zosmf apis

This depends on the maintenance level of z/OSMF. The check status endpoint did not require valid authentication until a recent PTF was released.

File: package.json [hunk 3]
```diff
@@ -64,7 +64,7 @@
       "@tootallnate/once": "^3.0.1",
       "ajv@6": "^6.14.0",
       "ajv@8": "^8.18.0",
-      "basic-ftp@5": "^5.3.0",
+      "basic-ftp@5": "^5.2.3",
```
Comment (traeok) [inline package.json]: I think we'll want the latest version of `basic-ftp` to align w/ what's in `main` 👍

**Review by traeok — COMMENTED** [review]
Looks like there was an issue with syncing dependencies.

Consider checking out the `package.json` and lock file from `main` and pushing that up to resolve:

```bash
git fetch --all
git checkout main -- ./package.json
git checkout main -- ./pnpm-lock.yaml
```

Plan to approve once that's addressed 👍

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks for the fix @jellypuno
