### PR TITLE
fix(regression): Handle uncaught exception in `ZoweTreeNode.getProfile`

### LINKED ISSUE #3772: Cannot hide or remove profile from tree after deleting config
**Describe the bug**

**To Reproduce**

1. Create a team config in Zowe Explorer UI

The default name of `zosmf` is used:

Image

2. Use VS Code to delete the `zowe.config.json` and `zowe.schema.json` files. 
3. "Manage Profile" and select "Hide"

Image

4. You get an error:

```
Error running command zowe.profileManagement: Zowe Explorer Profiles Cache error: Could not find profile named: zosmf.. This is likely caused by the extension that contributes zowe.profileManagement.
```

**Expected behavior**

I should be able to remove ("hide") a profile from the UI that I deleted.  

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Do you have secure credentials enabled?
- (Optional) Are you using a custom credential manager?

**Additional context**

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #3772 and resolves multiple scenarios due to a `ZoweTreeNode.getProfile` regression in the Zowe Explorer API. The `loadNamedProfile` function was called outside of a try/catch block, causing exceptions from the function to be propagated to the caller/API consumer (breaking change).

If the user:
- deletes a profile from their team configuration
- renames a profile in the team configuration
- deletes the team configuration entirely
- renames the team configuration file

The matching profile node is not removed from any of the trees, because the Zowe Explorer core logic abruptly terminated due to the uncaught exception.

## Release Notes

Milestone: 3.3.0

Changelog:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [x] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [x] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

File: packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts [hunk 1]
```diff
@@ -76,8 +77,17 @@ export class ZoweTreeNode extends vscode.TreeItem {
      * @returns {imperative.IProfileLoaded}
      */
     public getProfile(profilesCache?: ProfilesCache): imperative.IProfileLoaded {
-        if (this.profile != null && profilesCache?.loadNamedProfile != null) {
-            return profilesCache.loadNamedProfile(this.profile.name);
+        if (this.profile != null && profilesCache != null) {
+            try {
+                return profilesCache.loadNamedProfile(this.profile.name);
```
Comment (zFernand0) [inline packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts:82]: Thanks for catching this issue.
In theory, there is one more function that's calling `loadNamedProfile`

CallStack:
`ssoLogin|ssoLogout > getServiceProfile > getServiceProfileForAuthPurposes`

Not sure that we should be super concerned with that other use, since it's using the `cache` 😋 

However, we should warn extenders that may rely on the `loadNamedProfile` 😅

**Review by zFernand0 — DISMISSED** [review]
LGTM! 😋 
---
Thanks for addressing the issue so quickly.
The profiles just go away now (as they used to before) 😋

File: packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts (hunk 1 above)
Comment (traeok) [reply packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts:82]: I was tempted to refactor this as well, but after looking into the logic, I realized the function has always thrown an error if the profile does not exist. Since this code has thrown an error for 5 years in this scenario, I think its best to keep it as-is to preserve this behavior (as we're already past the major version boundary).

I would expect the `ssoLogin` function to throw an error if the profile does not exist, so I believe this thrown exception is acceptable.

**Review by JillieBeanSim — DISMISSED** [review]
thanks for working on this @traeok this does resolve the delete config and add to workspace issues but I do see with the profile name change scenario the tree does get updated but I end up in a 401 credential loop and not sure why when token auth in place even after re-logging in after the name change I get successful login then a 401 prompt

**Comment by traeok** [comment]
@JillieBeanSim Thanks for reviewing. The scenario you mentioned definitely sounds problematic. But, this also means that the same behavior would be seen in `main` before #3673 was merged, correct? 

If so, in the interest of quickly reverting this major breaking change & regression, I think its best to fix that scenario in a different PR.

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
---
Thanks for the clear changelog too! 🙏
