### PR TITLE
Warn users about files reopened from previous session

### LINKED ISSUE #2758: Error on activation when temp files are left from the previous session
**Describe the bug**

When use Zowe Explorer (ZE), user may get a `Cannot read property of 'undefined' (reading 'pattern')` 

**Note:** Newer (prerelease included) versions of ZE presented `(reading 'binary')` 

**To Reproduce**

1. Open dataset or USS file
2. Edit the contents (without saving)
3. Reload VSCode
4. Save the contents

**Expected behavior**

No error, but rather a conflict-resultion window so that I can resolve any conflicts

**Screenshots**

image

**Desktop (please complete the following information):**

- OS: Any
- Zowe Explorer Version: vNext (and 2.14.1)
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Additional context**

kudos to @t1m0thyj for the help on this! 🙏🏽

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Resolves #2758 by improving user experience for data set or USS files left open in the last VS Code session. This can happen when the VS Code window is reloaded or restarted after terminating abnormally.

* Stores the node properties `binary`, `encoding`, and `etag` in local storage so they will persist after reload
* Recreates old nodes at launch time using properties in local storage so that old edits can still be uploaded
* Shows warning message and inline diagnostic for any "recovered" data sets or USS files that are detected

image

## Release Notes

Milestone: 2.15.2

Changelog: Fixed issue where files left open in prior VS Code session cannot be uploaded to mainframe after window is reloaded.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

File: packages/zowe-explorer/src/uss/utils.ts [hunk 1]
```diff
@@ -75,7 +75,7 @@ export function disposeClipboardContents(): void {
 }
 
 export async function autoDetectEncoding(node: IZoweUSSTreeNode, profile?: imperative.IProfileLoaded): Promise<void> {
-    if (node.binary || node.encoding !== undefined) {
+    if (node == null || node.binary || node.encoding !== undefined) {
```
Comment (zFernand0) [inline packages/zowe-explorer/src/uss/utils.ts:78]: Do we have specific behavior defined for when `node.encoding === null`?

**Review by zFernand0 — DISMISSED** [review]
LGTM! 😋 
I left a few questions, but approving anyways since it seems to work just fine 😋 

Also, it would seem that this PR may not need to be ported over to next 🥳

File: packages/zowe-explorer/src/utils/LocalFileManagement.ts [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+                node[k] = v;
+            }
+            updateOpenFiles(isZoweDatasetTreeNode(node) ? TreeProviders.ds : TreeProviders.uss, filename, node);
+        }
+    }
+
+    public static storeFileInfo(node: IZoweDatasetTreeNode | IZoweUSSTreeNode, filename?: string): void {
+        const fileInfo = ZoweLocalStorage.getValue<Record<string, IFileInfo>>("zowe.fileInfoCache") ?? {};
+        if (filename == null) {
+            filename = isZoweDatasetTreeNode(node) ? node.getDsDocumentFilePath() : node.getUSSDocumentFilePath();
```
[the remark this answers is not in the document]
Comment (t1m0thyj) [reply packages/zowe-explorer/src/utils/LocalFileManagement.ts:70]: Thanks for catching this, the method was failing when called with a job node. Should be fixed in https://github.com/zowe/vscode-extension-for-zowe/pull/2760/commits/48e6de740a2a39b6ea7835d4a80e9387a927e86f

File: packages/zowe-explorer-api/CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,14 @@ All notable changes to the "zowe-explorer-api" extension will be documented in t
 
 ### New features and enhancements
 
+- Added optional method `getDsDocumentFilePath` to `IZoweDatasetTreeNode` interface.
```
Comment (anaxceron) [inline packages/zowe-explorer-api/CHANGELOG.md:9]: We should include an issue/pr link for this. Also, we should explain why we made this change and/or the benefit of this change to the user.

File: packages/zowe-explorer/i18n/sample/src/utils/TempFolder.i18n.json [hunk 4]
```diff
@@ -1,4 +1,5 @@
 {
   "moveTempFolder.error": "Error encountered when creating temporary folder!",
-  "deactivate.error": "Unable to delete temporary folder. "
+  "deactivate.error": "Unable to delete temporary folder. ",
+  "findRecoveredFiles.message": "One or more files remained open in your last VS Code session. To prevent losing your updates, check the Problems view to see the list of files and re-save them to upload edits to the mainframe."
```
Comment (anaxceron) [inline packages/zowe-explorer/i18n/sample/src/utils/TempFolder.i18n.json:4]: Suggesting two small edits: "To **avoid** losing your updates ... re-save them to upload **the changes** to the mainframe."

File: packages/zowe-explorer/src/utils/TempFolder.ts [hunk 5]
```diff
@@ -133,3 +140,37 @@ export async function hideTempFolder(zoweDir: string): Promise<void> {
...
+            };
+            LocalFileManagement.addRecoveredFile(document, treeOpts);
+            LocalFileManagement.loadFileInfo(new ZoweUSSNode(treeOpts), document.fileName);
+        }
+    }
+    if (LocalFileManagement.recoveredFileCount > 0) {
+        Gui.warningMessage(
+            localize(
+                "findRecoveredFiles.message",
+                "One or more files remained open in your last VS Code session. To prevent losing your updates, check the Problems view to see the list of files and re-save them to upload edits to the mainframe."
```
Comment (anaxceron) [inline packages/zowe-explorer/src/utils/TempFolder.ts:172]: See my previous comment re: suggested edits

**Review by anaxceron — DISMISSED** [review]
Looks good. Made two small comments.

File: packages/zowe-explorer/src/uss/utils.ts (hunk 1 above)
Comment (t1m0thyj) [reply packages/zowe-explorer/src/uss/utils.ts:78]: I believe @traeok is handling this in the FileSystemProvider branch - instead of `binary: boolean` and `encoding: string`, we can pass the `ZosEncoding` object around for all encoding related operations 😋

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Review by traeok — DISMISSED** [review]
LGTM, thanks @t1m0thyj

**Comment by adam-wolfe** [comment]
Not necessarily a problem, but if I make a modification, reload VS Code, then close the file without saving, the problem stays in my VS Code problems list until I reopen the data set and save it.

**Comment by adam-wolfe** [comment]
One thing I saw with this PR:
1. If I close the tab with unsaved changes and choose "Don't save", the problem remains in my problem list, but clicking on the problem creates a tab that says "The editor could not be opened because the file was not found."

A few things I ran into that may not be directly related to this PR:
1. If you have an expired APIML token, when you open VS Code (and have previously unsaved changes) and try to save your changes, you are asked to reauthenticate. However, after successfully authenticating and trying to save again, you are asked to reauthenticate. This loops until you reload VS Code. 
2. If I close the tab with unsaved changes and chose "Save", I get an error message: "TypeError: Cannot read properties of null (reading 'binary')" with the stack trace (built from commit 26067b27dfca931c9812b502acb7662f8fd65399):
```
[2024/03/11 09:23:10] [ERROR] TypeError: Cannot read properties of null (reading 'binary')
{
  errorDetails: [TypeError: Cannot read properties of null (reading 'binary')
  	at c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:13:14092
  	at Generator.next (<anonymous>)
  	at c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:13:12953
  	at new Promise (<anonymous>)
  	at r (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:13:12698)
  	at S (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:13:14011)
  	at c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:29:298148
  	at v.d (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:151992)
  	at v.withProgress (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:151855)
  	at Object.withProgress (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:32751)
  	at e.withProgress (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:21:509474)
  	at Object.<anonymous> (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:29:298058)
  	at Generator.next (<anonymous>)
  	at s (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.15.0-SNAPSHOT\out\src\extension.js:29:267132)
  	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)],
  label: 'dev.zosmf',
  moreInfo: undefined
}
```

**Comment by adam-wolfe** [comment]
This has solved some of the issues.

I may be getting too deep into an edge case that could be handled as a separate issue, but I'm still running into an issue where I:
1. Use a profile that goes through the APIML
2. Make edit to a data set member
3. Close VS Code without saving
4. APIML token expires
5. Reopen VS Code
6. Attempt to close the tab with the unsaved changes
7. Click "Save" in the dialog box that appears
    - Interestingly, I do not run into an issue if I save normally (CTRL+S)
9. Reauthenticate with the APIML
10. Attempt to close the tab again
11. Click "Save" in the dialog box (or just try to save with CTRL+S)
12. Receive error: "TypeError: Cannot read properties of null (reading 'binary')"

```
[2024/03/12 09:45:11] [DEBUG] File was saved -- determining whether the file is a USS file or Data set.
 Comparing (case insensitive) c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\resources\temp\_D_\dev.zosmf\me.REXX.EXEC(AW#123).rexx against directory c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\resources\temp\_D_andc:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\resources\temp\_U_
[2024/03/12 09:45:11] [DEBUG] File is a data set-- saving 
[2024/03/12 09:45:11] [TRACE] ZoweSaveQueue.push called.
[2024/03/12 09:45:11] [TRACE] ZoweSaveQueue.all called.
[2024/03/12 09:45:11] [TRACE] ZoweSaveQueue.processNext called.
[2024/03/12 09:45:11] [TRACE] dataset.actions.saveFile called.
[2024/03/12 09:45:11] [DEBUG] Requested to save data set c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\resources\temp\_D_\dev.zosmf\me.REXX.EXEC(AW#123).rexx
[2024/03/12 09:45:11] [TRACE] Profiles.getInstance called.
[2024/03/12 09:45:11] [INFO] Saving file me.REXX.EXEC(AW#123)
[2024/03/12 09:45:12] [TRACE] shared.utils.concatChildNodes called.
[2024/03/12 09:45:12] [TRACE] shared.utils.concatChildNodes called.
[2024/03/12 09:45:12] [ERROR] TypeError: Cannot read properties of null (reading 'binary')
{
  errorDetails: [TypeError: Cannot read properties of null (reading 'binary')
  	at c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:13:14092
  	at Generator.next (<anonymous>)
  	at c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:13:12953
  	at new Promise (<anonymous>)
  	at r (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:13:12698)
  	at S (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:13:14011)
  	at c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:29:298529
  	at v.d (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:151992)
  	at v.withProgress (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:151855)
  	at Object.withProgress (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:32751)
  	at e.withProgress (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:21:511223)
  	at Object.<anonymous> (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:29:298439)
  	at Generator.next (<anonymous>)
  	at s (c:\Users\me\.vscode\extensions\zowe.vscode-extension-for-zowe-2.16.0-SNAPSHOT\out\src\extension.js:29:267217)
  	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)],
  label: 'dev.zosmf',
  moreInfo: undefined
}
```

**Review by anaxceron — APPROVED** [review]

**Review by anaxceron — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Comment by t1m0thyj** [comment]
Rebased against maintenance branch, should be ready for review now 🙂

**Review by zFernand0 — APPROVED** [review]
Changes LGTM! 😋 

I know you just went through the trouble of rebasing to `maintenance`.

If the desire is to release this as a 2.15.2 version, please update the PR description and remove the 2.16.0 milestone 😋 

And afterwards, we can have another PR going from `maintenance` to `main`.

File: packages/zowe-explorer/src/dataset/DatasetTree.ts [hunk 6]
```diff
@@ -1513,9 +1515,15 @@ export class DatasetTree extends ZoweTreeProvider implements IZoweTree<IZoweData
...
+    public static onDidCloseTextDocument(this: void, doc: vscode.TextDocument): Promise<void> {
         if (doc.uri.fsPath.includes(globals.DS_DIR)) {
-            updateOpenFiles(TreeProviders.ds, doc.uri.fsPath, null);
+            return ZoweSaveQueue.all().then(() => {
+                if (!vscode.workspace.textDocuments.find(({ uri }) => uri.fsPath === doc.uri.fsPath)?.isDirty) {
+                    // Remove document from cache only if there are no pending unsaved changes
+                    updateOpenFiles(TreeProviders.ds, doc.uri.fsPath, null);
+                    LocalFileManagement.removeRecoveredFile(doc);
+                }
+            });
```
Comment (traeok) [inline packages/zowe-explorer/src/dataset/DatasetTree.ts:1526]: I think we discussed this offline at one point - but what happens if one of the queued save operations fails? Should we still run this logic in a `.catch` block to see if the given URI was saved anyway?

File: packages/zowe-explorer/src/shared/utils.ts [hunk 7]
```diff
@@ -133,7 +135,7 @@ export function getAppName(isTheia: boolean): "Theia" | "VS Code" {
  * @param {IZoweTreeNode} node
  */
 export function getDocumentFilePath(label: string, node: IZoweTreeNode): string {
-    const dsDir = globals.DS_DIR;
+    const dsDir = globals.DS_DIR || "";
```
Comment (traeok) [inline packages/zowe-explorer/src/shared/utils.ts:138]: I was under the impression that we set `globals.DS_DIR` during initialization in `defineGlobals` - is this logical OR still needed here?

File: packages/zowe-explorer/src/uss/USSTree.ts [hunk 8]
```diff
@@ -947,9 +949,15 @@ export class USSTree extends ZoweTreeProvider implements IZoweTree<IZoweUSSTreeN
...
+    public static onDidCloseTextDocument(this: void, doc: vscode.TextDocument): Promise<void> {
         if (doc.uri.fsPath.includes(globals.USS_DIR)) {
-            updateOpenFiles(TreeProviders.uss, doc.uri.fsPath, null);
+            return ZoweSaveQueue.all().then(() => {
+                if (!vscode.workspace.textDocuments.find(({ uri }) => uri.fsPath === doc.uri.fsPath)?.isDirty) {
+                    // Remove document from cache only if there are no pending unsaved changes
+                    updateOpenFiles(TreeProviders.uss, doc.uri.fsPath, null);
+                    LocalFileManagement.removeRecoveredFile(doc);
+                }
+            });
```
Comment (traeok) [inline packages/zowe-explorer/src/uss/USSTree.ts:960]: I noticed this logic is almost the same as in `DatasetTree` (except for the variable access in `TreeProviders`).
Could this be condensed into a single function, so it only needs to be maintained in one place moving forward?

**Review by traeok — COMMENTED** [review]
Thanks @t1m0thyj! This looks good, just had a couple of comments and a question about save failures.

**Review by JillieBeanSim — COMMENTED** [review]
I think this will be fine for another patch release since the issue is labeled high sev & priority.  If all agree I think it would be good to set this up to push release too.

File: packages/zowe-explorer/src/dataset/DatasetTree.ts (hunk 6 above)
Comment (t1m0thyj) [reply packages/zowe-explorer/src/dataset/DatasetTree.ts]: The ZoweSaveQueue should catch and handle any errors during save operations, so I don't think we need to catch them here.
https://github.com/zowe/zowe-explorer-vscode/blob/0ddb5d94f937cb151a54189c5ca2226f3d2ddf3d/packages/zowe-explorer/src/abstract/ZoweSaveQueue.ts#L62

File: packages/zowe-explorer/src/shared/utils.ts (hunk 7 above)
Comment (t1m0thyj) [reply packages/zowe-explorer/src/shared/utils.ts:139]: I think this fallback was needed for tests and I copied it from the USS implementation of `getDocumentFilePath`. Discussed this offline and ideally we would fix tests so they define globals and we could get rid of the fallback here, but it may not be worthwhile since this code is going away in v3 with the FileSystemProvider.

File: packages/zowe-explorer/src/dataset/DatasetTree.ts (hunk 6 above)
Comment (traeok) [reply packages/zowe-explorer/src/dataset/DatasetTree.ts]: Thanks for the clarification!

**Review by traeok — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
🥳
