### PR TITLE
Fix profile loading regressions in 3.4.0

### LINKED ISSUE #4094: Zowe Explorer failing to activate due to undefined session state
**Describe the bug**

One of my colleagues is facing an issue where zowe explorer is failing to activate fully (it is loading favourites and data set tree fine, but nothing else). First problem: there was no problems in the logs or in the notification message (until they try to run a command which has the failed to run command error as the extension failed to activate fully). I only found the real error by looking in the developer tools log.

This error message "Activating extension 'Zowe.vscode-extension-for-zowe' failed: Profile is using token type but missing a token." is strange because I made sure he had all the correct config files in the correct places (`zowe.config.json`, `zowe.schema.json`, `settings/imperative.json`) and we do not and have never used token authentication type. Our config specifies user, password in the base profile. So it is very weird why it comes to this error message.

I see that the extender retry #3830  from a few months ago introduced this new code in the stat() function which it is calling several times over to fetch the info for each of the data set favourites. 

Image

So I put some debug statements into the code and sent him the build which I then used to gather some information on what the difference is between his and my sessions.

Left side is his logs, right side is my logs

Image

His session type is none and in `ISessionKeys`, his array is missing `user, password, base64EncodedAuth`. 

So I had a look in credential manager (`cmdkey /list`) both outside of vscode and in vscode terminal but in neither places are the zowe secure config props. So there are no credentials in the credential manager currently. 

**Solution**: We rolled back to version 3.3.0 (so before extender retry branch) and ZE was able to activate. I then got him to enter his credentials into it and checked that we could open a data set so credentials were saved in credential manager. Then, we updated ZE back to 3.4.1 and the extension was now able to activate. This confirmed my theory that the lack of credentials somehow was causing it to be in a weird state and him not being able to enter his credentials because of it failing to activate was the blocker. So there is definately a bug in the code there somewhere on >3.4.0.

**To Reproduce**

No idea how to reproduce, user logged onto vscode one day to get this issue. Note: they did not have a custom imperative.json file at the time (so using default windows credential manager with default persistence settings).

**Expected behavior**

1. Profile and activation error to be in logs or shown to user, not hidden away in the developer console
2. The extension to activate so he can enter his credentials

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win11
- Zowe Explorer Version: 3.4.1

**Additional context**

### LINKED ISSUE #4105: Profile should default to basic auth when parent profile has multiple auth types
**Describe the bug**

When using a z/OSMF profile that expects basic auth, if the parent profile defines multiple auth types (both basic and token), then ZE tries to use token auth instead.

**To Reproduce**

1. Create a new Team Config with base profile that contains `user`, `password`, and `tokenValue` in the secure array:
    ```json
    {
        "$schema": "./zowe.schema.json",
        "profiles": {
            "zosmf_basic": {
                "type": "zosmf",
                "properties": {
                    "port": 443
                },
                "secure": []
            },
            "project_base": {
                "type": "base",
                "properties": {
                    "host": "example.com",
                    "tokenType": "apimlAuthenticationToken"
                },
                "secure": [
                    "user",
                    "password",
                    "tokenValue"
                ]
            }
        },
        "defaults": {
            "zosmf": "zosmf_basic",
            "base": "project_base"
        },
        "autoStore": true
    }
    ```
2. Open the directory containing the Team Config in VS Code.
3. Right-click the "zosmf_basic" profile in the ZE tree, and select "Manage Profile", then "Add Credentials".
4. Enter user name and password for the "zosmf_basic" profile.
5. Try to perform an action like searching for a DS pattern with the "zosmf_basic" profile.
6. Notice that you are prompted to log in to the API ML.

**Expected behavior**

The "zosmf_basic" profile property should use basic auth, since it doesn't have an `authOrder` property to override the default order of precedence for auth types.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS 26.3
- Zowe Explorer Version: 3.4.1 (bug first seen in 3.3.1, works in 3.3.0)

**Additional context**

Discussed with @zFernand0 and adding the following check to the top of `Profiles.profileHasSecureToken` fixes the issue. If we make this change, we should do internal validation with teams who use token auth extensively.
```typescript
        const sessTypeFromProf = AuthHandler.sessTypeFromProfile(theProfile);
        if (
            sessTypeFromProf !== imperative.SessConstants.AUTH_TYPE_TOKEN &&
            sessTypeFromProf !== imperative.SessConstants.AUTH_TYPE_BEARER &&
            sessTypeFromProf !== imperative.SessConstants.AUTH_TYPE_NONE
        ) {
            // The authOrder property has already been processed and determined
            // that basic or cert auth should be used, so we shouldn't check
            // for a token value.
            return false;
        }
```

### LINKED ISSUE #4110: zFTP: Must have user & password OR base64 credentials on startup
**Describe the bug**

When I started VS Code after updating to the latest release, I encountered the following error notification from my z/FTP profile:

Image

The logs indicate that this happens for all trees at start-up:

```
[2026/03/12 13:33:53] [ERROR] Error: Must have user & password OR base64 encoded credentials
{
  errorDetails: [s [Error]: Must have user & password OR base64 encoded credentials
  	at W.buildSession (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:428:15339)
  	at new h (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:428:13686)
  	at new y (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:433:2678)
  	at new W (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\main.extension.js:57:19988)
  	at Y.getSession (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\main.extension.js:57:20878)
  	at ci.<anonymous> (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:90:950)
  	at Generator.next (<anonymous>)
  	at c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:24559
  	at new Promise (<anonymous>)
  	at We (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:24379)
  	at ci.addSingleSession (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:90:626)
  	at ci.<anonymous> (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:21647)
  	at Generator.next (<anonymous>)
  	at n (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:13827)] {
    mDetails: {
      msg: 'Must have user & password OR base64 encoded credentials',
      additionalDetails: "For CLI usage, see '<your-cli> auth login <service> --help'"
    },
    mMessage: 'Must have user & password OR base64 encoded credentials'
  },
  apiType: 'mvs',
  profile: undefined
}
[2026/03/12 13:33:53] [DEBUG] No data set favorites found.
[2026/03/12 13:33:53] [DEBUG] No USS favorites found.
[2026/03/12 13:33:53] [ERROR] Error: Must have user & password OR base64 encoded credentials
{
  errorDetails: [s [Error]: Must have user & password OR base64 encoded credentials
  	at W.buildSession (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:428:15339)
  	at new h (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:428:13686)
  	at new y (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:433:2678)
  	at new W (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\main.extension.js:57:19988)
  	at O.getSession (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\main.extension.js:57:20878)
  	at Wi.<anonymous> (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:204:18966)
  	at Generator.next (<anonymous>)
  	at c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:204:11190
  	at new Promise (<anonymous>)
  	at _e (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:204:11010)
  	at Wi.addSingleSession (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:204:18646)
  	at Wi.<anonymous> (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:21647)
  	at Generator.next (<anonymous>)
  	at n (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:13827)] {
    mDetails: {
      msg: 'Must have user & password OR base64 encoded credentials',
      additionalDetails: "For CLI usage, see '<your-cli> auth login <service> --help'"
    },
    mMessage: 'Must have user & password OR base64 encoded credentials'
  },
  apiType: 'uss',
  profile: undefined
}
[2026/03/12 13:33:53] [DEBUG] No USS favorites found.
[2026/03/12 13:33:53] [DEBUG] No jobs favorites found.
[2026/03/12 13:33:53] [ERROR] Error: Must have user & password OR base64 encoded credentials
{
  errorDetails: [s [Error]: Must have user & password OR base64 encoded credentials
  	at W.buildSession (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:428:15339)
  	at new h (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:428:13686)
  	at new y (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\vendors.extension.js:433:2678)
  	at new W (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\main.extension.js:57:19988)
  	at a.getSession (c:\Users\#########\.vscode\extensions\zowe.zowe-explorer-ftp-extension-3.4.2-universal\out\src\main.extension.js:57:20878)
  	at wt.<anonymous> (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:135:10539)
  	at Generator.next (<anonymous>)
  	at c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:135:8021
  	at new Promise (<anonymous>)
  	at Ke (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:135:7841)
  	at wt.addSingleSession (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:135:10219)
  	at wt.<anonymous> (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:21647)
  	at Generator.next (<anonymous>)
  	at n (c:\Users\#########\.vscode\extensions\zowe.vscode-extension-for-zowe-3.4.2-universal\out\src\main.extension.js:87:13827)] {
    mDetails: {
      msg: 'Must have user & password OR base64 encoded credentials',
      additionalDetails: "For CLI usage, see '<your-cli> auth login <service> --help'"
    },
    mMessage: 'Must have user & password OR base64 encoded credentials'
  },
  apiType: 'jes',
  profile: undefined
}
```

**However, I can still use my FTP profiles...** 🤔 

I believe its related to session building based on the stack trace. I would not expect Zowe Explorer to try using the session or doing validation until the profile is interacted with. Automatic Profile Validation is ON.

**To Reproduce**

Still working out details. All that was apparent on the first encounter is: I'm using my pre-existing global config w/ 3.4.1 (no errors there) and then updated to 3.4.2.

**Expected behavior**

Should not get any errors at start-up from potentially missing creds in a session.
This seems related to missing session credentials as seen in #4094 , but wanted to track it as I'm only seeing an error coming from the z/FTP extension, and the extension still activates.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Do you have secure credentials enabled?
- (Optional) Are you using a custom credential manager?

**Additional context**

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

* (ZE) Fixes an issue where loading profiles could wrongly assume token authentication if parent profile defines multiple auth types
* (ZE API) Fixes an issue where `Gui.openFileDialog` method could fail if default URL with `vscode-remote` scheme is provided
* (ZE FTP) Fixes an issue where the FTP extension failed to load `zftp` profiles that do not have credentials defined

## Release Notes

Milestone: 3.4.3

Changelog:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**All checks must pass before this pull request is reviewed by the Zowe Explorer squad.**

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`
- [ ] New ZE APIs are tested with extender types that haven't adopted yet to determine breaking changes. Can use Zowe zFTP marketplace extension.

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have tested new functionality with the FTP extension and profile verifying no extender profile type breakages introduced
- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by anaxceron — APPROVED** [review]

**Review by zFernand0 — COMMENTED** [review]
LGTM! 😋 
---
Thanks for adding a workaround for the VSCode issue 🙏 
Do we have an GH issue we can paste here for reference?

**Review by zFernand0 — APPROVED** [review]

File: packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ export abstract class AbstractFtpApi implements MainframeInteraction.ICommon {
                 user: loadedProfile.user,
                 password: loadedProfile.password,
                 rejectUnauthorized: loadedProfile.rejectUnauthorized,
-                type: "basic",
+                type: loadedProfile.user && loadedProfile.password ? "basic" : "none",
```
Comment (traeok) [inline packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts:48]: Thanks for the FTP fix 😋 the related error notification kept pestering me at startup lol

**Review by traeok — APPROVED** [review]
Tested and LGTM, thanks Timothy for the fixes!

**Review by anaxceron — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
---
Thanks for re-requesting reviews 🙏
